### ISSUE TITLE
Find a new name for detections

### ISSUE THREAD

**Issue by tdegueul** [alien-tools/breakbot#39]

**Comment by jrfaller** [comment]
Hi huys! Glad to have an issue assigned 😁! To start: what's wrong with broken location ?

**Comment by lmove** [comment]
Hello! I believe the main issue is that "broken location" is too similar to "broken declaration", which is associated with the library declaration that introduces a breaking change.

**Comment by jrfaller** [comment]
OK, I see and I completely agree with you. Moreover `location` is very abstract. We could even use it for the library side, so it's confusing. What about broken use / broken usage? I think that this one is clearly on the client side. Maybe for the library side we could even use broken definition. This way we would be using a def / use terminology that is kind of conveying the right idea? WDYT?

**Comment by lmove** [comment]
I like this idea! But then, I am having trouble differentiating between the "broken definition" and the "breaking change" itself. How do both terms relate to each other? Will the "breaking change" be considered just as the type labeling the action that impacts the "broken definition"?

**Comment by tdegueul** [comment]
Same argument as @lmove, too similar. Actually, I think _breaking change_ is just the right term on the library's side—and that's how it's used in the literature (though it's a _little_ confusing in terms of types vs. instances but no big deal). We should revert _broken declaration_ to _breaking change_ in the code IMHO.

On the client's side, I'm not sure. _Location_ is too abstract, but it's because we're not clear yet on the granularity of "detections" (AST node, line, source code location, etc). @jrfaller I think broken use/usage is really ugly though 😛 What we're actually doing is impact analysis: something with _impacted_? Dunno.

**Comment by jrfaller** [comment]
Tricky question!

The way I see it we have 
* the `breaking change` is for instance `changed type of method X.Foo to Bar`
* the `broken definition` is `X::Foo` and this is probably where I am wrong because the broken declaration is not independent of the change right?
* a sample `broken use` is `Baz value = X.foo()`

**Comment by lmove** [comment]
I agree with @tdegueul regarding the use of "breaking change" on the library side. But "broken use" does not sound too bad to me, to be honest :p

**Comment by jrfaller** [comment]
+1 to the fact that I do not find broken use an ugly term! I particularly love the fact that it is a sort of tribute to the good old def-use data-flow analysis (such as https://en.wikipedia.org/wiki/Use-define_chain)

**Comment by tdegueul** [comment]
> Tricky question!
> 
> The way I see it we have
> 
>     * the `breaking change` is for instance `changed return type of method X.Foo to Bar`
> 
>     * the `broken definition` is `X::Foo` and this is probably where I am wrong because the broken declaration is not independent of the change right?
> 
>     * a sample `broken use` is `Baz value = X.foo()`

+1 to all of that. A breaking change is the whole thing (declaration + type of BC), but it still makes sense to use (colloquially) broken definition/declaration for the declaration being affected by the change.

It just doesn't sound great in my ears, but I sometimes have that feeling for no reason ;) So this is it for now, unless we find better!

**Comment by jrfaller** [comment]
OK guys, thanks to our great discussion, I think I have clarified something in my head regarding the concepts we need for our theory. Currently I have this :

* `definition`: statement the are used to define stuff you can use in a client
* `use`: statement in a client that makes use of a definition
* `breaking changes`: an abstract kind of change that when applied on a definition can lead to a use in the client not to compile/run/link anymore
* `broken definition`: a `breaking change` on a given `definition`
* `broken use`: a `broken definition`associated to a given `use`

I am overly pedantic here but at least I have the impression that this is consistent 😆

**Comment by lmove** [comment]
Nice summary! I like it but there is still the risk of using the _breaking change_ term in a slightly different way compared to the state of the art (as @tdegueul already mentioned). However, I really like it and it can also help in clarifying the concepts we use when talking about software evolution. I would personally go for the _broken def/use_ terms as @jrfaller suggests!

Now, I think we are reducing the _breaking change_ to a type of action, which does not completely feel okayish yet.

**Comment by jrfaller** [comment]
I agree, although I am not completely sure that the literature refers to a breaking change as an abstract or instantiated concept, and I think that in fact its use is conflated to refer to both. Anyway we need something to name the abstract change in itself since we refer to it in our report (currently we have `kind` as a column name in the report to name this), it could be `breaking change type` and then `broken definition` becomes `breaking change`. But now I am really fond of the def/use shenanigans 😄

**Comment by tdegueul** [comment]
Solved in Maracas and in https://github.com/alien-tools/breakbot/commit/04c4dab1b18e283b17c1b66c92eb4230dc868cc8.

**Comment by jrfaller** [comment]
Great work!
